// Interface phrases only. Official place names and route identifiers are data.
// No Māori translation has received fluent-speaker review yet.
export const languageKey = 'along-language-v1';
export const languages = Object.freeze({
  en: {name: 'English', tag: 'en-NZ', status: 'source'},
  mi: {name: 'Te reo Māori', tag: 'mi-NZ', status: 'draft'},
});

// Named placeholders must match between languages. Text is never HTML.
export const messages = {
  'language.label': {en: 'Language', mi: 'Reo'},
  'language.draft': {en: 'Draft translation. This te reo Māori translation was generated by AI and may contain mistakes. It has not yet been reviewed by a fluent speaker.', mi: null},
  'language.fallback': {en: 'Some information is still shown in English.', mi: "Kei te whakaaturia tonu ētahi kōrero ki te reo Ingarihi."},
  'language.session': {en: 'Your language choice will last for this session only; device storage is unavailable.', mi: "Ka mau tō kōwhiringa reo mō tēnei wā whakamahi anake; kāore e taea te rokiroki ki tēnei pūrere."},
  'language.changed': {en: 'Language changed to {language}.', mi: "Kua hurihia te reo ki {language}."},
  'flow.destination.title': {en: 'Where would you like to go?', mi: 'Kei te hiahia haere koe ki hea?'},
  'flow.origin.title': {en: 'Where are you travelling from?', mi: 'Kei te haere mai koe i hea?'},
  'flow.review.title': {en: 'Review your journey', mi: 'Arotakengia tō haerenga'},
  'flow.reviewNearby.title': {en: 'Review departure preferences', mi: "Arotakengia ngā manakohanga wehenga"},
  'flow.options.title': {en: 'Choose your journey', mi: 'Kōwhiria tō haerenga'},
  'flow.follow.title': {en: 'Your next step', mi: 'Tō hipanga e whai ake nei'},
  'flow.arrived.title': {en: 'You’re there.', mi: 'Kua tae koe.'},
  'flow.nearby.title': {en: 'Your next ride nearby', mi: "Tō ekenga e whai ake nei, e tata ana"},
  'flow.destination.progress': {en: 'Plan a journey', mi: 'Whakaritea he haerenga'},
  'flow.origin.progress': {en: 'Choose your starting place', mi: "Kōwhiria tō wāhi tīmatanga"},
  'flow.review.progress': {en: 'Time and travel needs', mi: "Te wā me ngā hiahia haerenga"},
  'flow.options.progress': {en: 'Choose a route', mi: "Kōwhiria he ara"},
  'flow.follow.progress': {en: 'Follow your journey', mi: "Whāia tō haerenga"},
  'flow.arrived.progress': {en: 'Journey complete', mi: 'Kua oti te haerenga'},
  'flow.nearby.progress': {en: 'Compare nearby stops', mi: "Whakatauritea ngā tūnga e tata ana"},
  'flow.destinationSelected': {en: 'Destination already selected: {place}', mi: "Kua kōwhiria te ūnga: {place}"},
  'action.back': {en: '← Back', mi: '← Hoki'},
  'action.newJourney': {en: 'New journey', mi: 'He haerenga hou'},
  'action.understood': {en: 'Understood', mi: 'Kua mārama'},
  'action.settings': {en: 'Settings', mi: 'Ngā tautuhinga'},
  'action.closeSettings': {en: 'Close settings', mi: 'Katia ngā tautuhinga'},
  'action.home': {en: 'Along home', mi: "Te kāinga o Along"},
  'action.skip': {en: 'Skip to current task', mi: "Haere ki te mahi o nāianei"},
  'action.chooseOrigin': {en: 'Choose starting place →', mi: "Kōwhiria te wāhi tīmatanga →"},
  'action.review': {en: 'Review journey →', mi: 'Arotakengia te haerenga →'},
  'action.reviewNearby': {en: 'Review departure preferences →', mi: "Arotakengia ngā manakohanga wehenga →"},
  'action.find': {en: 'Find my way →', mi: "Kimihia tōku ara →"},
  'action.findNearby': {en: 'Show nearby departures →', mi: "Whakaaturia ngā wehenga e tata ana →"},
  'action.nextStep': {en: 'Next step →', mi: 'Te hipanga e whai ake nei →'},
  'action.previousStep': {en: '← Previous step', mi: '← Te hipanga o mua'},
};

// Draft journey controls; review in the context of their screens.
Object.assign(messages, {
  "place.destination": {
    "en": "Destination (to)",
    "mi": "Ūnga (ki)"
  },
  "place.origin": {
    "en": "Starting place (from)",
    "mi": "Wāhi tīmatanga (mai i)"
  },
  "place.help": {
    "en": "Enter a street address, station or stop, then choose a suggestion.",
    "mi": "Tāurutia he wāhitau, he teihana, he tūnga rānei, kātahi ka kōwhiri i tētahi huatau."
  },
  "place.originHelp": {
    "en": "Or enter the address or stop you will leave from, then choose a suggestion.",
    "mi": "Tāurutia rānei te wāhitau, te tūnga rānei ka wehe atu koe, kātahi ka kōwhiri i tētahi huatau."
  },
  "place.placeholder": {
    "en": "Street address or stop",
    "mi": "He wāhitau, he tūnga rānei"
  },
  "place.destinations": {
    "en": "Destinations",
    "mi": "Ngā ūnga"
  },
  "place.origins": {
    "en": "Starting places",
    "mi": "Ngā wāhi tīmatanga"
  },
  "place.from": {
    "en": "From",
    "mi": "Mai i"
  },
  "place.to": {
    "en": "To",
    "mi": "Ki"
  },
  "action.nearby": {
    "en": "Just find a nearby departure",
    "mi": "Kimihia noa he wehenga e tata ana"
  },
  "action.explore": {
    "en": "Explore a bus, train or ferry route",
    "mi": "Tūhuratia he ara pahi, tereina, waka kōpiko rānei"
  },
  "action.editOrigin": {
    "en": "Change starting place",
    "mi": "Hurihia te wāhi tīmatanga"
  },
  "action.editDestination": {
    "en": "Change destination",
    "mi": "Hurihia te ūnga"
  },
  "action.swap": {
    "en": "Swap origin and destination",
    "mi": "Whakawhitia te wāhi tīmatanga me te ūnga"
  },
  "action.now": {
    "en": "Set departure to now",
    "mi": "Whakaritea te wehenga mō nāianei"
  },
  "action.return": {
    "en": "Plan the return journey →",
    "mi": "Whakaritea te haerenga hoki →"
  },
  "action.another": {
    "en": "Go somewhere else",
    "mi": "Haere ki wāhi kē"
  },
  "action.changeSearch": {
    "en": "Change time or travel preferences",
    "mi": "Hurihia te wā, ngā manakohanga haerenga rānei"
  },
  "action.compareNearby": {
    "en": "Compare nearby departures instead",
    "mi": "Whakatauritea ngā wehenga e tata ana"
  },
  "action.nearbyEdit": {
    "en": "Change starting place or access preferences",
    "mi": "Hurihia te wāhi tīmatanga, ngā manakohanga urunga rānei"
  },
  "action.nearbyPlan": {
    "en": "Plan a journey to a destination",
    "mi": "Whakaritea he haerenga ki tētahi ūnga"
  },
  "usual.title": {
    "en": "Your usual journeys",
    "mi": "Ō haerenga auau"
  },
  "preference.title": {
    "en": "Journey preferences",
    "mi": "Ngā manakohanga haerenga"
  },
  "preference.date": {
    "en": "Departure date",
    "mi": "Te rā wehe"
  },
  "preference.time": {
    "en": "Auckland time",
    "mi": "Te wā o Tāmaki Makaurau"
  },
  "preference.travelBy": {
    "en": "Travel by",
    "mi": "Haere mā runga"
  },
  "mode.bus": {
    "en": "▣ Bus",
    "mi": "▣ Pahi"
  },
  "mode.train": {
    "en": "▥ Train",
    "mi": "▥ Tereina"
  },
  "mode.ferry": {
    "en": "≈ Ferry",
    "mi": "≈ Waka kōpiko"
  },
  "preference.maxWalk": {
    "en": "Maximum walk at each end",
    "mi": "Te roanga hīkoi mōrahi i ia pito"
  },
  "preference.pace": {
    "en": "Walking or rolling pace",
    "mi": "Te tere hīkoi, te tere neke mā runga tūru wīra rānei"
  },
  "preference.avoid": {
    "en": "Avoid mapped steps and barriers",
    "mi": "Karohia ngā arawhata me ngā tauārai kua maherehia"
  },
  "preference.confirmed": {
    "en": "Only confirmed accessible stops and vehicles",
    "mi": "Ko ngā tūnga me ngā waka anake kua whakaūngia te āhei ki te uru"
  },
  "sort.label": {
    "en": "Sort journeys",
    "mi": "Kōmakahia ngā haerenga"
  },
  "sort.arrival": {
    "en": "Earliest arrival",
    "mi": "Te taenga wawe rawa"
  },
  "sort.transfers": {
    "en": "Fewest changes",
    "mi": "Ngā whakawhitinga ruarua rawa"
  },
  "sort.walking": {
    "en": "Least walking",
    "mi": "Te hīkoi poto rawa"
  },
  "journey.scheduled": {
    "en": "Transit times are scheduled. Walking and access links are estimates.",
    "mi": "He wā kua whakaritea ngā wā waka. He whakatau tata ngā hīkoi me ngā ara urunga."
  },
  "journey.advance": {
    "en": "Advance when you are ready. Along is not tracking your progress. Times are scheduled.",
    "mi": "Haere whakamua ina rite koe. Kāore a Along e aroturuki ana i tō ahunga whakamua. He wā kua whakaritea ēnei."
  },
  "journey.whole": {
    "en": "Whole journey",
    "mi": "Te haerenga katoa"
  },
  "journey.about": {
    "en": "About these journeys",
    "mi": "Mō ēnei haerenga"
  }
});

Object.assign(messages, {
  "preference.summary": {
    "en": "Depart {time} · {modes}{access}",
    "mi": "Wehe i te {time} · {modes}{access}"
  },
  "preference.allModes": {
    "en": "Bus, train & ferry",
    "mi": "Pahi, tereina me te waka kōpiko"
  },
  "preference.chooseTransport": {
    "en": "Choose transport",
    "mi": "Kōwhiria he waka"
  },
  "preference.now": {
    "en": "now",
    "mi": "nāianei"
  },
  "preference.barriers": {
    "en": " · Avoid barriers",
    "mi": " · Karohia ngā tauārai"
  },
  "preference.confirmedOnly": {
    "en": " · Confirmed access only",
    "mi": " · Ko te urunga kua whakaūngia anake"
  },
  "preference.moreTime": {
    "en": " · More walking time",
    "mi": " · He wā hīkoi anō"
  },
  "mode.busWord": {
    "en": "bus",
    "mi": "pahi"
  },
  "mode.trainWord": {
    "en": "train",
    "mi": "tereina"
  },
  "mode.ferryWord": {
    "en": "ferry",
    "mi": "waka kōpiko"
  },
  "pace.usual": {
    "en": "Usual · 4.5 km/h",
    "mi": "Te tere auau · 4.5 km/h"
  },
  "pace.unhurried": {
    "en": "Unhurried · 3.6 km/h",
    "mi": "Āta haere · 3.6 km/h"
  },
  "pace.moreTime": {
    "en": "More time · 2.9 km/h",
    "mi": "He wā anō · 2.9 km/h"
  },
  "minutes.5": {
    "en": "5 minutes",
    "mi": "5 meneti"
  },
  "minutes.10": {
    "en": "10 minutes",
    "mi": "10 meneti"
  },
  "minutes.15": {
    "en": "15 minutes",
    "mi": "15 meneti"
  },
  "minutes.20": {
    "en": "20 minutes",
    "mi": "20 meneti"
  }
});

Object.assign(messages, {
  "save.places": {
    "en": "☆ Save these places",
    "mi": "☆ Tiakina ēnei wāhi"
  },
  "save.saved": {
    "en": "★ Saved places",
    "mi": "★ Ngā wāhi kua tiakina"
  },
  "save.help": {
    "en": "Remember this start and destination, without a route or departure time.",
    "mi": "Puritia tēnei wāhi tīmatanga me tēnei ūnga, kāore he ara, he wā wehe rānei."
  },
  "save.done": {
    "en": "Starting place and destination saved. No departure time is saved.",
    "mi": "Kua tiakina te wāhi tīmatanga me te ūnga. Kāore he wā wehe i tiakina."
  },
  "save.removed": {
    "en": "Saved places and any service preference removed.",
    "mi": "Kua tangohia ngā wāhi kua tiakina me ngā manakohanga ratonga."
  },
  "service.prefer": {
    "en": "☆ Prefer these services",
    "mi": "☆ Kōwhiria ēnei ratonga hei manakohanga"
  },
  "service.preferred": {
    "en": "★ Preferred services",
    "mi": "★ Ngā ratonga e manakohia ana"
  },
  "service.instead": {
    "en": "☆ Prefer these services instead",
    "mi": "☆ Kōwhiria ēnei ratonga kē hei manakohanga"
  },
  "service.help": {
    "en": "Optionally remember these service numbers for next time. This also saves the places; departure times are checked again.",
    "mi": "Ki te hiahia koe, puritia ēnei tau ratonga mō muri ake. Ka tiakina hoki ngā wāhi; ka tirohia anō ngā wā wehe."
  },
  "service.removed": {
    "en": "Service preference removed. Saved places are kept.",
    "mi": "Kua tangohia te manakohanga ratonga. Ka puritia ngā wāhi kua tiakina."
  },
  "service.saved": {
    "en": "Places saved with preferred services: {services}. Times will be checked when you reopen it.",
    "mi": "Kua tiakina ngā wāhi me ngā ratonga e manakohia ana: {services}. Ka tirohia ngā wā ina huaki anō koe."
  },
  "service.compare": {
    "en": "Compare without saved route preference",
    "mi": "Whakatauritea me te kore manakohanga ara kua tiakina"
  },
  "follow.step": {
    "en": "Step {step} of {total}",
    "mi": "Hipanga {step} o te {total}"
  },
  "follow.arrived": {
    "en": "I’ve arrived",
    "mi": "Kua tae ahau"
  },
  "journey.walkTo": {
    "en": "Walk to {place}",
    "mi": "Hīkoi ki {place}"
  },
  "journey.use": {
    "en": "Use this journey →",
    "mi": "Whakamahia tēnei haerenga →"
  },
  "journey.savedRoute": {
    "en": "Your saved route",
    "mi": "Tō ara kua tiakina"
  },
  "journey.another": {
    "en": "Another option",
    "mi": "He kōwhiringa anō"
  },
  "journey.walkRoll": {
    "en": "Walk or roll",
    "mi": "Hīkoi, neke rānei mā runga tūru wīra"
  },
  "journey.noChanges": {
    "en": "No changes",
    "mi": "Kāore he whakawhitinga"
  },
  "journey.oneChange": {
    "en": "{count} change",
    "mi": "{count} whakawhitinga"
  },
  "journey.changes": {
    "en": "{count} changes",
    "mi": "{count} whakawhitinga"
  },
  "journey.walkMinutes": {
    "en": "{minutes} min walking / rolling",
    "mi": "{minutes} meneti hīkoi / neke mā runga tūru wīra"
  },
  "journey.minuteUnit": {
    "en": "min",
    "mi": "meneti"
  },
  "journey.walk": {
    "en": "Walk",
    "mi": "Hīkoi"
  },
  "journey.otherOne": {
    "en": "See {count} other option",
    "mi": "Tirohia tētahi atu kōwhiringa ({count})"
  },
  "journey.otherMany": {
    "en": "See {count} other options",
    "mi": "Tirohia ētahi atu kōwhiringa ({count})"
  },
  "journey.tryAnother": {
    "en": "Let’s try another option.",
    "mi": "Me whakamātau he kōwhiringa anō."
  },
  "journey.nonePreferences": {
    "en": "No route was found within these preferences.",
    "mi": "Kāore i kitea he ara e hāngai ana ki ēnei manakohanga."
  },
  "journey.adjust": {
    "en": "Adjust journey preferences →",
    "mi": "Whakatikaina ngā manakohanga haerenga →"
  },
  "journey.loading": {
    "en": "Finding your way through Auckland…",
    "mi": "Kei te kimi i tō ara mā Tāmaki Makaurau…"
  },
  "journey.oneWay": {
    "en": "{count} way to get there",
    "mi": "{count} ara kia tae atu"
  },
  "journey.ways": {
    "en": "{count} ways to get there",
    "mi": "{count} ara kia tae atu"
  },
  "journey.noneWindow": {
    "en": "No journey found in this window",
    "mi": "Kāore i kitea he haerenga i tēnei wā"
  },
  "journey.announced": {
    "en": "{count} journey options. Earliest arrival {time}.",
    "mi": "E {count} ngā kōwhiringa haerenga. Ko te taenga wawe rawa ko te {time}."
  },
  "journey.noneAnnounced": {
    "en": "No journey found with these preferences.",
    "mi": "Kāore i kitea he haerenga e hāngai ana ki ēnei manakohanga."
  },
  "mode.busTitle": {
    "en": "Bus",
    "mi": "Pahi"
  },
  "mode.trainTitle": {
    "en": "Train",
    "mi": "Tereina"
  },
  "mode.ferryTitle": {
    "en": "Ferry",
    "mi": "Waka kōpiko"
  }
});

Object.assign(messages, {
  "walk.stationAccess": {
    "en": "Station access is estimated. Check the entrance, lift and platform signs.",
    "mi": "He whakatau tata te ara uru ki te teihana. Tirohia ngā tohu mō te tomokanga, te ararewa me te tūāpapa."
  },
  "walk.directions": {
    "en": "Walking directions · {metres} m",
    "mi": "Ngā tohutohu hīkoi · {metres} m"
  },
  "walk.estimated": {
    "en": " (access link estimated)",
    "mi": " (he whakatau tata te ara urunga)"
  },
  "walk.checkSigns": {
    "en": "Follow local crossing and access signs. Unmapped barriers and changes may affect this path.",
    "mi": "Whāia ngā tohu whakawhiti me ngā tohu urunga o te wāhi. Ka pā pea ngā tauārai kāore i te mahere me ngā panonitanga ki tēnei ara."
  },
  "place.addressType": {
    "en": "Street address",
    "mi": "Wāhitau"
  },
  "place.stationType": {
    "en": "Station",
    "mi": "Teihana"
  },
  "place.stopType": {
    "en": "Stop {code}",
    "mi": "Tūnga {code}"
  },
  "place.noMatch": {
    "en": "No matching place. Try the street number, street name and suburb.",
    "mi": "Kāore he wāhi e hāngai ana. Whakamātauria te tau whare, te ingoa tiriti me te takiwā."
  },
  "error.destination": {
    "en": "Choose a destination from the suggestions.",
    "mi": "Kōwhiria he ūnga mai i ngā huatau."
  },
  "error.origin": {
    "en": "Choose a starting place from the suggestions, or use your location.",
    "mi": "Kōwhiria he wāhi tīmatanga mai i ngā huatau, whakamahia rānei tō tauwāhi."
  },
  "error.places": {
    "en": "Choose both places from the suggestions.",
    "mi": "Kōwhiria ngā wāhi e rua mai i ngā huatau."
  },
  "location.use": {
    "en": "Use my current location",
    "mi": "Whakamahia tōku tauwāhi o nāianei"
  },
  "location.finding": {
    "en": "Finding your location…",
    "mi": "Kei te kimi i tō tauwāhi…"
  },
  "location.unavailable": {
    "en": "Location is unavailable in this browser. Choose a stop instead.",
    "mi": "Kāore e wātea te tauwāhi i tēnei pūtirotiro. Kōwhiria kē he tūnga."
  },
  "location.failed": {
    "en": "Could not get your location. You can choose a stop or station instead.",
    "mi": "Kāore i taea te tiki i tō tauwāhi. Ka taea te kōwhiri he tūnga, he teihana rānei."
  },
  "location.selected": {
    "en": "Current location selected. Continue when ready.",
    "mi": "Kua kōwhiria tō tauwāhi o nāianei. Haere tonu ina rite koe."
  }
});

Object.assign(messages, {
  "explore.loading": {
    "en": "Loading details…",
    "mi": "Kei te uta i ngā taipitopito…"
  },
  "explore.routeTitle": {
    "en": "Route details",
    "mi": "Ngā taipitopito ara"
  },
  "explore.title": {
    "en": "Explore a route",
    "mi": "Tūhuratia he ara"
  },
  "explore.walkTitle": {
    "en": "Walking connection",
    "mi": "Ara hīkoi tūhono"
  },
  "explore.walkEstimate": {
    "en": "Walking duration and access links are estimates.",
    "mi": "He whakatau tata te roanga hīkoi me ngā ara urunga."
  },
  "explore.stationStop": {
    "en": "Station or stop",
    "mi": "Teihana, tūnga rānei"
  },
  "explore.access": {
    "en": "Accessibility at this location is not verified. Check entrances, crossings and any lifts before travelling.",
    "mi": "Kāore anō kia whakaūngia te āhei ki te uru ki tēnei wāhi. Tirohia ngā tomokanga, ngā whakawhitinga me ngā ararewa i mua i te haere."
  },
  "board.heading": {
    "en": "Departures from {time} · {date}",
    "mi": "Ngā wehenga mai i te {time} · {date}"
  },
  "board.limit": {
    "en": "Next two hours from the downloaded timetable. Delays, cancellations and vehicle positions are not shown here.",
    "mi": "Ko ngā hāora e rua e whai ake nei mai i te wātaka kua tikiakehia. Kāore e whakaaturia ngā takaroa, ngā whakakorenga me ngā tauwāhi waka i konei."
  },
  "board.at": {
    "en": "AT Mobile: live times and vehicle tracking ↗",
    "mi": "AT Mobile: ngā wā o nāianei me te aroturuki waka ↗"
  },
  "board.online": {
    "en": "(online · opens AT’s website)",
    "mi": "(ā-ipurangi · ka huaki te pae tukutuku a AT)"
  },
  "board.caption": {
    "en": "Scheduled departures — not live",
    "mi": "Ngā wehenga kua whakaritea — ehara i te wā tūturu"
  },
  "board.time": {
    "en": "Time",
    "mi": "Wā"
  },
  "board.route": {
    "en": "Route",
    "mi": "Ara"
  },
  "board.destination": {
    "en": "Destination",
    "mi": "Ūnga"
  },
  "board.none": {
    "en": "No scheduled departures in this window. These are not live times.",
    "mi": "Kāore he wehenga kua whakaritea i tēnei wā. Ehara ēnei i ngā wā tūturu."
  },
  "map.show": {
    "en": "Show street map",
    "mi": "Whakaaturia te mahere tiriti"
  },
  "map.internet": {
    "en": "Needs internet · OpenStreetMap",
    "mi": "Me whai ipurangi · OpenStreetMap"
  },
  "map.help": {
    "en": "Street tiles load from OpenStreetMap only when requested. Route lines and stop locations use downloaded AT data.",
    "mi": "Ka utaina ngā mahere tiriti mai i OpenStreetMap ina tonoa anake. Ka whakamahia ngā raraunga AT kua tikiakehia mō ngā ara me ngā tūnga."
  },
  "map.controls": {
    "en": "Map. Use arrow keys to pan and plus or minus to zoom.",
    "mi": "Mahere. Whakamahia ngā pātuhi pere ki te neke, me te tāpiri, te tango rānei ki te topa."
  },
  "explore.noServices": {
    "en": "No services in the downloaded timetable for {date}.",
    "mi": "Kāore he ratonga i te wātaka kua tikiakehia mō te {date}."
  },
  "explore.stopsFrom": {
    "en": "{count} stops · from {place}",
    "mi": "{count} tūnga · mai i {place}"
  },
  "explore.choose": {
    "en": "Scheduled services for {date}. Choose a direction or branch to see its full path and times.",
    "mi": "Ngā ratonga kua whakaritea mō te {date}. Kōwhiria he ahunga, he peka rānei kia kite i tōna ara katoa me ngā wā."
  },
  "explore.branches": {
    "en": "Other directions and branches ({count})",
    "mi": "Ētahi atu ahunga me ngā peka ({count})"
  },
  "explore.scheduled": {
    "en": "Scheduled times. This is a service route, not a live vehicle position.",
    "mi": "He wā kua whakaritea. He ara ratonga tēnei, ehara i te tauwāhi waka o nāianei."
  },
  "explore.geometry": {
    "en": "Published AT route geometry.",
    "mi": "Te āhua o te ara i whakaputaina e AT."
  },
  "explore.noGeometry": {
    "en": "Route geometry unavailable; the map shows stop locations only.",
    "mi": "Kāore e wātea te āhua o te ara; ko ngā tūnga anake kei te mahere."
  },
  "explore.run": {
    "en": "Service departing its first stop",
    "mi": "Te ratonga e wehe ana i tōna tūnga tuatahi"
  },
  "explore.filter": {
    "en": "Find a street or stop on this direction",
    "mi": "Kimihia he tiriti, he tūnga rānei i tēnei ahunga"
  },
  "explore.filterHint": {
    "en": "For example, Symonds",
    "mi": "Hei tauira, Symonds"
  },
  "explore.filterHelp": {
    "en": "Matches stop names. A street with no matching stop may still be on the route: check the map. Other branches can take different paths.",
    "mi": "Ka rapua ngā ingoa tūnga. Kei runga tonu pea tētahi tiriti i te ara ahakoa kāore he tūnga e hāngai ana: tirohia te mahere. He ara rerekē pea tō ētahi atu peka."
  },
  "explore.lastStop": {
    "en": " · Last stop",
    "mi": " · Te tūnga whakamutunga"
  },
  "explore.noPickup": {
    "en": " · No regular pickup",
    "mi": " · Kāore he ekenga auau"
  },
  "explore.matches": {
    "en": "{count} matching stops in this direction",
    "mi": "E {count} ngā tūnga e hāngai ana i tēnei ahunga"
  },
  "explore.search": {
    "en": "Route number or name",
    "mi": "Te tau, te ingoa rānei o te ara"
  },
  "explore.searchHint": {
    "en": "For example, 70 or Western",
    "mi": "Hei tauira, 70, Western rānei"
  },
  "explore.noRoutes": {
    "en": "No matching routes.",
    "mi": "Kāore he ara e hāngai ana."
  }
});

Object.assign(messages, {
  'map.zoomIn': {en:'Zoom in',mi:'Topa mai'},
  'map.zoomOut': {en:'Zoom out',mi:'Topa atu'},
});

Object.assign(messages, {
  "settings.title": {
    "en": "Your commute, your control.",
    "mi": "Tō haerenga, tō mana whakahaere."
  },
  "settings.course": {
    "en": "About this course project",
    "mi": "Mō tēnei kaupapa akoranga"
  },
  "course.risk": {
    "en": "Use at your own risk.",
    "mi": "Māu anō te mōrea o te whakamahi."
  },
  "course.warning": {
    "en": "Along was created as an exercise for an AI-assisted coding course. It is experimental and is not an official Auckland Transport service. Routes, times, walking directions and accessibility information may be incomplete, outdated or incorrect. Check your journey and access requirements with AT before travelling.",
    "mi": "I hangaia a Along hei mahi mō tētahi akoranga waehere e tautokona ana e te atamai horihori. He whakamātautau tēnei, ehara i te ratonga mana a Auckland Transport. He kōrero hē, tawhito, kāore rānei i oti mō ngā ara, ngā wā, ngā tohutohu hīkoi me te āhei ki te uru. Tirohia tō haerenga me ō hiahia urunga ki a AT i mua i te haere."
  },
  "settings.privacy": {
    "en": "Search history and current location stay on this device. If you allow journey sharing, saved places and service preferences can be exchanged with your connected devices. An optional relay helps permitted devices reconnect while Along is open. It sees connection metadata; shared journeys are encrypted. No Along server stores your journeys.",
    "mi": "Ka ako a Along i ngā rapunga haerenga kua angitu, kāore mā te aroturuki papamuri. Ka noho ō rapunga, ō ara kua tiakina me ō manakohanga ki tēnei pūrere. Kāore he pūkete, kāore hoki e tukuna ake tō hītori haerenga."
  },
  "settings.suggest": {
    "en": "Suggest my usual journeys",
    "mi": "Huatautia ōku haerenga auau"
  },
  "settings.learningHelp": {
    "en": "Suggestions reflect how often you search, the time of day and weekday versus weekend. You can always plan somewhere different.",
    "mi": "Ka hāngai ngā huatau ki te auau o ō rapunga, te wā o te rā, me ngā rā mahi, ngā rā whakatā rānei. Ka taea tonu te whakarite haerenga ki wāhi kē."
  },
  "settings.forget": {
    "en": "Forget history and saved places",
    "mi": "Mukua tōku hītori haerenga"
  },
  "settings.device": {
    "en": "On this device",
    "mi": "Kei tēnei pūrere"
  },
  "settings.updates": {
    "en": "Service updates",
    "mi": "Ngā whakahoutanga ratonga"
  },
  "settings.checkUpdate": {
    "en": "Check for an app update",
    "mi": "Tirohia he whakahoutanga taupānga"
  },
  "settings.aboutLink": {
    "en": "About Along on GitHub ↗",
    "mi": "Mō Along i GitHub ↗"
  },
  "settings.aboutAria": {
    "en": "About Along on GitHub (opens in a new tab)",
    "mi": "Mō Along i GitHub (ka huaki ki tētahi ripa hou)"
  },
  "course.made": {
    "en": "How Along was made",
    "mi": "Te hanga o Along"
  },
  "course.process": {
    "en": "The human directs the design and tries the app; the AI writes and changes the code, investigates problems and runs technical checks. No coding by the human is required.",
    "mi": "Mā te tangata te hoahoa e ārahi me te taupānga e whakamātau; mā te atamai horihori te waehere e tuhi, e whakarerekē, ngā raruraru e tūhura, me ngā arowhai hangarau e whakahaere. Kāore te tangata e mate ki te tuhi waehere."
  },
  "course.links": {
    "en": "Explore the course material on GitHub (opens in a new tab):",
    "mi": "Tūhuratia ngā rauemi akoranga i GitHub (ka huaki ki tētahi ripa hou):"
  },
  "course.goal": {
    "en": "Project goal and completion criteria",
    "mi": "Te whāinga kaupapa me ngā paearu whakaoti"
  },
  "course.analysis": {
    "en": "Thematic analysis of the design conversation",
    "mi": "Te tātari ā-kaupapa o te kōrerorero hoahoa"
  },
  "course.guide": {
    "en": "Course guide and exercises",
    "mi": "Te aratohu akoranga me ngā mahi"
  },
  "offline.title": {
    "en": "Works offline. Live information is optional.",
    "mi": "Ka mahi tuimotu. Māu e kōwhiri ngā kōrero o nāianei."
  },
  "offline.explanation": {
    "en": "Downloaded address search and scheduled planning work offline. Optional AT checks use your configured personal key to request current information directly from AT. Unavailable or unmatched information leaves the schedule in place. The portal supplies downloads and updates, not journey calculations.",
    "mi": "I muri i te whakarite, ka mahi tuimotu te rapu wāhitau me te whakamahere haerenga ā-wātaka ki tō pūrere. Ki te kōwhiria, ka tāpiri ngā kōrero AT ā-ipurangi i ngā matapae me ngā whakatūpato o nāianei. Kāore anō kia whakahohea te hononga wā-tūturu o te taupānga tūmatanui; ka ahu ngā wā haerenga i te wātaka kua tikiakehia. Mā te tomokanga ngā tikiake me ngā whakahoutanga e tuku, ehara i ngā tātaitanga haerenga."
  },
  "offline.guide": {
    "en": "Install on your device · offline and privacy guide",
    "mi": "Tāutahia ki tō pūrere · aratohu tuimotu me te tūmataitinga"
  },
  "offline.refresh": {
    "en": "Update downloaded timetable",
    "mi": "Whakahoutia te wātaka kua tikiakehia"
  },
  "offline.install": {
    "en": "Install Along",
    "mi": "Tāutahia a Along"
  },
  "offline.apple": {
    "en": "On iPhone or iPad, open the Share menu and choose Add to Home Screen. Offline storage remains subject to your browser’s storage settings.",
    "mi": "I runga i te iPhone, te iPad rānei, huakina te tahua Share, ka kōwhiri i te Add to Home Screen. Ka hāngai tonu te rokiroki tuimotu ki ngā tautuhinga rokiroki o tō pūtirotiro."
  },
  "learning.active": {
    "en": "Your searches help your usual journeys find their way here. Stored only on this device.",
    "mi": "Mā ō rapunga ka puta mai ō haerenga auau ki konei. Ka rokirokia ki tēnei pūrere anake."
  },
  "learning.paused": {
    "en": "Journey learning is paused. Saved routes stay available, and every new journey is yours to choose.",
    "mi": "Kua whakatārewatia te ako haerenga. Ka wātea tonu ngā ara kua tiakina, ā, māu ia haerenga hou e kōwhiri."
  },
  "storage.failed": {
    "en": "This browser could not save your preferences. They will last for this session only.",
    "mi": "Kāore i taea e tēnei pūtirotiro te tiaki ō manakohanga. Ka mau mō tēnei wā whakamahi anake."
  },
  "learning.cleared": {
    "en": "Your journey history and saved routes have been cleared.",
    "mi": "Kua mukua tō hītori haerenga me ō ara kua tiakina."
  }
});

Object.assign(messages, {
  "nearby.heading": {
    "en": "Which stop should I head to?",
    "mi": "Me haere ahau ki tēhea tūnga?"
  },
  "nearby.refresh": {
    "en": "Refresh nearby departures",
    "mi": "Whakahoutia ngā wehenga e tata ana"
  },
  "nearby.filter": {
    "en": "Filter departures",
    "mi": "Tātarihia ngā wehenga"
  },
  "nearby.show": {
    "en": "Show",
    "mi": "Whakaaturia"
  },
  "nearby.all": {
    "en": "All transport",
    "mi": "Ngā momo waka katoa"
  },
  "nearby.buses": {
    "en": "Buses",
    "mi": "Ngā pahi"
  },
  "nearby.trains": {
    "en": "Trains",
    "mi": "Ngā tereina"
  },
  "nearby.ferries": {
    "en": "Ferries",
    "mi": "Ngā waka kōpiko"
  },
  "nearby.direct": {
    "en": "Direct to my destination",
    "mi": "Haere tōtika ki tōku ūnga"
  },
  "nearby.about": {
    "en": "About these departures",
    "mi": "Mō ēnei wehenga"
  },
  "nearby.more": {
    "en": "Show more nearby stops",
    "mi": "Whakaaturia ētahi atu tūnga e tata ana"
  },
  "nearby.fewer": {
    "en": "Show fewer stops",
    "mi": "Whakaaturia kia iti ake ngā tūnga"
  },
  "nearby.context": {
    "en": "Within 800 m of {place}. Earliest departures with estimated time to walk are shown first.",
    "mi": "Kei roto i te 800 m o {place}. Ka whakaaturia tuatahitia ngā wehenga wawe me te wā hīkoi kua whakatau tatahia."
  },
  "nearby.loading": {
    "en": "Checking the stops around you…",
    "mi": "Kei te tirotiro i ngā tūnga e tata ana ki a koe…"
  },
  "nearby.chooseDestination": {
    "en": "Choose a destination to compare direct services heading there.",
    "mi": "Kōwhiria he ūnga hei whakataurite i ngā ratonga e haere tōtika ana ki reira."
  },
  "nearby.start": {
    "en": "Start with where you are.",
    "mi": "Tīmata ki tō wāhi o nāianei."
  },
  "nearby.startHelp": {
    "en": "Choose a starting stop, or use your location to compare services from stops around you.",
    "mi": "Kōwhiria he tūnga tīmatanga, whakamahia rānei tō tauwāhi hei whakataurite i ngā ratonga mai i ngā tūnga e tata ana ki a koe."
  },
  "nearby.checked": {
    "en": "Checked at {time}.",
    "mi": "I tirohia i te {time}."
  },
  "nearby.liveNote": {
    "en": "Live predictions where available.",
    "mi": "Ngā matapae o nāianei ina wātea."
  },
  "nearby.scheduledNote": {
    "en": "Scheduled departures · live updates are not connected.",
    "mi": "Ngā wehenga kua whakaritea · kāore ngā whakahoutanga wā-tūturu e hono ana."
  },
  "nearby.refreshNote": {
    "en": "Refresh when you need updated departure estimates.",
    "mi": "Whakahoutia ina hiahia koe ki ngā whakatau tata wehenga hou."
  },
  "nearby.directNote": {
    "en": "Showing direct services to your selected destination.",
    "mi": "Kei te whakaaturia ngā ratonga tōtika ki tō ūnga kua kōwhiria."
  },
  "nearby.mapped": {
    "en": "Walking times follow mapped paths at your selected pace, with estimated access links.",
    "mi": "Ka whai ngā wā hīkoi i ngā ara kua maherehia i tō tere kua kōwhiria, me ngā ara urunga kua whakatau tatahia."
  },
  "nearby.estimated": {
    "en": "Walking times use distance estimates at your selected pace, not walking directions.",
    "mi": "Ka whakamahia ngā whakatau tata tawhiti i tō tere kua kōwhiria mō ngā wā hīkoi, ehara i ngā tohutohu hīkoi."
  },
  "nearby.buffer": {
    "en": "Check crossings and station access. “Tight” allows a two-minute boarding buffer.",
    "mi": "Tirohia ngā whakawhitinga me te urunga ki te teihana. Mō te “Poto te wā”, ka tāpirihia he rua meneti mō te ekenga."
  },
  "nearby.none": {
    "en": "No upcoming services found.",
    "mi": "Kāore i kitea he ratonga e whai ake nei."
  },
  "nearby.noneDirect": {
    "en": "No upcoming direct services found.",
    "mi": "Kāore i kitea he ratonga tōtika e whai ake nei."
  },
  "nearby.try": {
    "en": "Try another stop, a different transport mode.",
    "mi": "Whakamātauria he tūnga kē, he momo waka kē rānei."
  },
  "nearby.tryDirect": {
    "en": "Try another stop, a different transport mode or switch off the direct-service filter.",
    "mi": "Whakamātauria he tūnga kē, he momo waka kē rānei, whakawetohia rānei te tātari ratonga tōtika."
  },
  "nearby.window": {
    "en": "We look up to two hours ahead within 800 metres, and up to 20 minutes along mapped walking paths when downloaded.",
    "mi": "Ka tirohia ngā hāora e rua e whai ake nei i roto i te 800 mita, ā, tae atu ki te 20 meneti mā ngā ara hīkoi kua maherehia ina kua tikiakehia."
  },
  "nearby.first": {
    "en": "First stop to consider",
    "mi": "Te tūnga tuatahi hei whakaaro māu"
  },
  "nearby.distance": {
    "en": "Stop {code} · {metres} m away",
    "mi": "Tūnga {code} · {metres} m te tawhiti"
  },
  "nearby.walk": {
    "en": "↗ {minutes} min walk est.",
    "mi": "↗ {minutes} meneti hīkoi, whakatau tata"
  },
  "nearby.tight": {
    "en": " · Tight on estimated walking time",
    "mi": " · Poto te wā mō te hīkoi kua whakatau tatahia"
  },
  "nearby.live": {
    "en": "● Live prediction",
    "mi": "● Matapae o nāianei"
  },
  "nearby.scheduled": {
    "en": "Scheduled",
    "mi": "Kua whakaritea"
  }
});

Object.assign(messages, {
  "status.preparing": {
    "en": "Preparing your timetable. The first offline download is about 40 MB.",
    "mi": "Kei te whakarite i tō wātaka. Tata ki te 40 MB te tikiake tuimotu tuatahi."
  },
  "status.streetsPreparing": {
    "en": "Preparing offline addresses and walking paths. This first download is about 24 MB.",
    "mi": "Kei te whakarite i ngā wāhitau me ngā ara hīkoi tuimotu. Tata ki te 24 MB tēnei tikiake tuatahi."
  },
  "status.streetsReady": {
    "en": "Street addresses and walking paths are ready offline.",
    "mi": "Kua rite ngā wāhitau me ngā ara hīkoi mō te whakamahi tuimotu."
  },
  "status.streetsSession": {
    "en": "Street search is ready for this session; device storage was unavailable.",
    "mi": "Kua rite te rapu tiriti mō tēnei wā whakamahi; kāore i wātea te rokiroki pūrere."
  },
  "status.addressesStored": {
    "en": "{count} addresses and the Auckland walking map are stored on this device.",
    "mi": "Kua rokirokia ngā wāhitau {count} me te mahere hīkoi o Tāmaki Makaurau ki tēnei pūrere."
  },
  "status.addressesSession": {
    "en": "{count} addresses and the Auckland walking map are available for this session.",
    "mi": "Kei te wātea ngā wāhitau {count} me te mahere hīkoi o Tāmaki Makaurau mō tēnei wā whakamahi."
  },
  "status.noAddresses": {
    "en": "Address search is unavailable. You can still choose a station or stop.",
    "mi": "Kāore e wātea te rapu wāhitau. Ka taea tonu te kōwhiri he teihana, he tūnga rānei."
  },
  "status.ready": {
    "en": "Along · offline ready",
    "mi": "Along · kua rite mō te tuimotu"
  },
  "status.offline": {
    "en": "Offline · journeys ready",
    "mi": "Tuimotu · kua rite ngā haerenga"
  },
  "status.session": {
    "en": "Along · session ready",
    "mi": "Along · kua rite mō tēnei wā whakamahi"
  },
  "status.streetSearch": {
    "en": "Preparing street search…",
    "mi": "Kei te whakarite i te rapu tiriti…"
  },
  "status.loading": {
    "en": "Loading AT timetable…",
    "mi": "Kei te uta i te wātaka AT…"
  },
  "status.unavailable": {
    "en": "Timetable unavailable",
    "mi": "Kāore e wātea te wātaka"
  },
  "status.overview": {
    "en": "{stops} AT stops. Timetable ends {expiry}.",
    "mi": "E {stops} ngā tūnga AT. Ka mutu te wātaka i te {expiry}."
  },
  "status.unknownExpiry": {
    "en": "{stops} AT stops. Timetable end date not specified.",
    "mi": "E {stops} ngā tūnga AT. Kāore te rā mutunga o te wātaka i tohua."
  },
  "status.stored": {
    "en": "Stored on this device.",
    "mi": "Kua rokirokia ki tēnei pūrere."
  },
  "status.notStored": {
    "en": "Storage was unavailable; an internet connection will be needed on your next visit.",
    "mi": "Kāore i wātea te rokiroki; me whai hononga ipurangi i tō hokinga mai."
  },
  "status.localRouting": {
    "en": "Scheduled routing runs entirely in your browser.",
    "mi": "Ka whakahaeretia katoatia te rapu ara ā-wātaka i tō pūtirotiro."
  },
  "status.refresh": {
    "en": "Downloading the latest timetable available on this server…",
    "mi": "Kei te tikiake i te wātaka hou e wātea ana i tēnei tūmau…"
  },
  "alerts.loading": {
    "en": "Checking service updates…",
    "mi": "Kei te tirotiro i ngā whakahoutanga ratonga…"
  },
  "alerts.none": {
    "en": "No alerts returned by AT.",
    "mi": "Kāore he whakatūpato i whakahokia mai e AT."
  },
  "alerts.offline": {
    "en": "Service updates need an internet connection. Your downloaded timetable is still available.",
    "mi": "Me whai hononga ipurangi mō ngā whakahoutanga ratonga. Kei te wātea tonu tō wātaka kua tikiakehia."
  },
  "alerts.website": {
    "en": "You can view current announcements on the AT website when online.",
    "mi": "Ka taea te tiro i ngā pānui o nāianei i te pae tukutuku a AT ina hono ki te ipurangi."
  }
});

Object.assign(messages, {
  "update.noActive": {
    "en": "No active app version was found.",
    "mi": "Kāore i kitea he putanga taupānga hohe."
  },
  "update.noVersion": {
    "en": "The active app did not confirm its version. Keep this page open and try again.",
    "mi": "Kāore te taupānga hohe i whakaū i tōna putanga. Waiho tēnei whārangi kia tuwhera, ka whakamātau anō."
  },
  "update.failed": {
    "en": "The new version could not be installed. Your existing app is still available.",
    "mi": "Kāore i taea te tāuta i te putanga hou. Kei te wātea tonu tō taupānga o nāianei."
  },
  "update.slow": {
    "en": "The update is taking longer than expected. Try again while online.",
    "mi": "Kei te roa ake te whakahoutanga i tā te whakaaro. Whakamātau anō ina hono ki te ipurangi."
  },
  "update.activation": {
    "en": "Could not activate the update. Please try again.",
    "mi": "Kāore i taea te whakahohe i te whakahoutanga. Whakamātau anō."
  },
  "update.replaced": {
    "en": "This update was replaced. Please try again.",
    "mi": "Kua whakakapihia tēnei whakahoutanga. Whakamātau anō."
  },
  "update.ready": {
    "en": "An app update is ready. Choose Update and reopen.",
    "mi": "Kua rite he whakahoutanga taupānga. Kōwhiria te Whakahou, ka huaki anō."
  },
  "update.current": {
    "en": "Your app is up to date.",
    "mi": "Kei te putanga hou tō taupānga."
  },
  "update.checking": {
    "en": "Checking and downloading the latest interface…",
    "mi": "Kei te tirotiro me te tikiake i te atanga hou…"
  },
  "update.https": {
    "en": "Open this page using the same HTTPS address as your installed Along app.",
    "mi": "Huakina tēnei whārangi mā te wāhitau HTTPS kotahi o tō taupānga Along kua tāutahia."
  },
  "update.already": {
    "en": "Already up to date — version {version}.",
    "mi": "Kei te putanga hou kē — putanga {version}."
  },
  "update.updated": {
    "en": "Updated to version {version}.",
    "mi": "Kua whakahoutia ki te putanga {version}."
  },
  "update.installed": {
    "en": "Installed version {version}.",
    "mi": "Kua tāutahia te putanga {version}."
  },
  "update.open": {
    "en": "Open Along →",
    "mi": "Huakina a Along →"
  },
  "update.title": {
    "en": "Update Along",
    "mi": "Whakahoutia a Along"
  },
  "update.intro": {
    "en": "Get the latest app interface. Your saved journeys and downloaded travel data stay on this device.",
    "mi": "Tikina te atanga taupānga hou. Ka noho ō haerenga kua tiakina me ngā raraunga haerenga kua tikiakehia ki tēnei pūrere."
  },
  "update.check": {
    "en": "Check for updates →",
    "mi": "Tirohia ngā whakahoutanga →"
  },
  "update.browser": {
    "en": "Use the same browser as your installed app. After updating, close and reopen the installed app.",
    "mi": "Whakamahia te pūtirotiro kotahi o tō taupānga kua tāutahia. I muri i te whakahou, katia, ka huaki anō i te taupānga kua tāutahia."
  },
  "update.back": {
    "en": "Back to Along",
    "mi": "Hoki ki Along"
  },
  "update.notice": {
    "en": "A new version of Along is ready.",
    "mi": "Kua rite he putanga hou o Along."
  },
  "update.apply": {
    "en": "Update and reopen",
    "mi": "Whakahou, ka huaki anō"
  }
});

Object.assign(messages, {
  "engine.route": {
    "en": "This route is not in the downloaded timetable.",
    "mi": "Kāore tēnei ara i te wātaka kua tikiakehia."
  },
  "engine.timetableVersion": {
    "en": "Please update Along to read this timetable.",
    "mi": "Whakahoutia a Along kia pānui i tēnei wātaka."
  },
  "engine.barriers": {
    "en": "Download the latest street map to avoid mapped steps and barriers.",
    "mi": "Tikina te mahere tiriti hou hei karo i ngā arawhata me ngā tauārai kua maherehia."
  },
  "engine.accessData": {
    "en": "Update the timetable to check vehicle and stop accessibility.",
    "mi": "Whakahoutia te wātaka hei tirotiro i te āhei ki te uru ki ngā waka me ngā tūnga."
  },
  "engine.place": {
    "en": "Choose an address or stop from the suggestions.",
    "mi": "Kōwhiria he wāhitau, he tūnga rānei mai i ngā huatau."
  },
  "engine.streetsLoading": {
    "en": "Street data is still loading. Stop-to-stop journeys are available now.",
    "mi": "Kei te uta tonu ngā raraunga tiriti. Kei te wātea ngā haerenga tūnga-ki-te-tūnga ināianei."
  },
  "engine.stop": {
    "en": "Choose a stop from the suggestions.",
    "mi": "Kōwhiria he tūnga mai i ngā huatau."
  },
  "engine.date": {
    "en": "Choose a valid date.",
    "mi": "Kōwhiria he rā whaimana."
  },
  "engine.dateRange": {
    "en": "This date is outside the downloaded timetable. Update your timetable in settings.",
    "mi": "Kei waho tēnei rā i te wātaka kua tikiakehia. Whakahoutia tō wātaka i ngā tautuhinga."
  },
  "engine.different": {
    "en": "Choose two different stops or addresses.",
    "mi": "Kōwhiria kia rua ngā tūnga, ngā wāhitau rānei e rerekē ana."
  },
  "engine.time": {
    "en": "Choose a valid departure time.",
    "mi": "Kōwhiria he wā wehe whaimana."
  },
  "engine.mode": {
    "en": "Select at least one transport mode.",
    "mi": "Kōwhiria kia kotahi neke atu te momo waka."
  },
  "engine.walk": {
    "en": "Choose a walking preference between 5 and 20 minutes.",
    "mi": "Kōwhiria he manakohanga hīkoi i waenga i te 5 me te 20 meneti."
  },
  "engine.sameStation": {
    "en": "These stops belong to the same station.",
    "mi": "Nō te teihana kotahi ēnei tūnga."
  },
  "engine.accessUnknown": {
    "en": "AT’s timetable does not confirm accessibility for the required stops. We cannot verify a wheelchair-accessible journey.",
    "mi": "Kāore te wātaka AT e whakaū i te āhei ki te uru ki ngā tūnga e hiahiatia ana. Kāore e taea te whakaū he haerenga e āhei ana mō te tūru wīra."
  },
  "engine.disconnected": {
    "en": "No connected stops within your walking preference. Try a longer walk or choose a nearby stop.",
    "mi": "Kāore he tūnga tūhono i roto i tō manakohanga hīkoi. Whakamātauria he hīkoi roa ake, kōwhiria rānei he tūnga e tata ana."
  },
  "engine.origin": {
    "en": "Choose a starting stop or use your location.",
    "mi": "Kōwhiria he tūnga tīmatanga, whakamahia rānei tō tauwāhi."
  },
  "engine.download": {
    "en": "Offline data could not be downloaded. Connect and try again.",
    "mi": "Kāore i taea te tikiake i ngā raraunga tuimotu. Hono atu, ka whakamātau anō."
  },
  "engine.compression": {
    "en": "Please use a current browser with offline compression support.",
    "mi": "Whakamahia he pūtirotiro hou e tautoko ana i te kōpeketanga tuimotu."
  },
  "engine.loading": {
    "en": "The timetable is still loading. Please try again in a moment.",
    "mi": "Kei te uta tonu te wātaka. Whakamātau anō ākuanei."
  },
  "engine.unknown": {
    "en": "Unknown request.",
    "mi": "He tono kāore i mōhiotia."
  },
  "engine.walkingVersion": {
    "en": "Please update the walking map.",
    "mi": "Whakahoutia te mahere hīkoi."
  },
  "engine.worker": {
    "en": "The route engine could not start. Reload Along to try again.",
    "mi": "Kāore i taea te tīmata te pūnaha rapu ara. Utaina anō a Along hei whakamātau anō."
  }
});

Object.assign(messages, {
  "usual.from": {
    "en": "From {place}",
    "mi": "Mai i {place}"
  },
  "usual.saved": {
    "en": "Saved",
    "mi": "Kua tiakina"
  },
  "usual.savedJourney": {
    "en": "Saved journey",
    "mi": "Haerenga kua tiakina"
  },
  "usual.searches": {
    "en": "{count} searches · one tap to plan",
    "mi": "{count} rapunga · pā kotahi hei whakamahere"
  },
  "usual.begin": {
    "en": "Your routine starts with a journey.",
    "mi": "Ka tīmata tō ritenga ki tētahi haerenga."
  },
  "usual.different": {
    "en": "Somewhere different? You’re in the right place.",
    "mi": "He wāhi kē? Kei te wāhi tika koe."
  },
  "usual.learnHelp": {
    "en": "Search a route a few times, or save one, and it will appear here.",
    "mi": "Rapua tētahi ara kia maha ngā wā, tiakina rānei tētahi, ā, ka puta mai ki konei."
  },
  "usual.pausedHelp": {
    "en": "Learning is paused. You can still save journeys yourself.",
    "mi": "Kua whakatā te ako. Ka taea tonu e koe te tiaki haerenga."
  },
  "usual.preference": {
    "en": "Saved preference:",
    "mi": "Manakohanga kua tiakina:"
  },
  "usual.match": {
    "en": "Matching services shown first, using the timetable for this search.",
    "mi": "Ka whakaaturia tuatahitia ngā ratonga e ōrite ana, mā te wātaka mō tēnei rapunga."
  },
  "usual.noMatch": {
    "en": "No match found in the next four hours with these travel preferences. Other options are shown when available.",
    "mi": "Kāore he ratonga ōrite i kitea i ngā hāora e whā e whai ake nei mō ēnei manakohanga haere. Ka whakaaturia ētahi atu kōwhiringa mēnā e wātea ana."
  }
});

Object.assign(messages, {
  "region.home": {
    "en": "Along home",
    "mi": "Kāinga Along"
  },
  "region.update": {
    "en": "App update",
    "mi": "Whakahou taupānga"
  },
  "region.navigation": {
    "en": "Journey navigation",
    "mi": "Whakatere haerenga"
  },
  "region.destination": {
    "en": "Choose a destination",
    "mi": "Kōwhiria he ūnga"
  },
  "region.origin": {
    "en": "Choose a starting place",
    "mi": "Kōwhiria he wāhi tīmatanga"
  },
  "region.review": {
    "en": "Review journey preferences",
    "mi": "Arotakengia ngā manakohanga haerenga"
  },
  "region.options": {
    "en": "Journey options",
    "mi": "Ngā kōwhiringa haerenga"
  },
  "region.follow": {
    "en": "Follow your journey",
    "mi": "Whāia tō haerenga"
  },
  "region.nearby": {
    "en": "Nearby departures",
    "mi": "Ngā wehenga e tata ana"
  },
  "action.closeAlerts": {
    "en": "Close updates",
    "mi": "Katia ngā whakahou"
  },
  "course.shortTitle": {
    "en": "Use at your own risk",
    "mi": "He mahi akoranga · Kei a koe te tūraru o te whakamahi."
  },
  "course.shortWarning": {
    "en": "Built for an AI-assisted coding course. Experimental, not an official AT app.",
    "mi": "I hangaia mō tētahi akoranga tuhi waehere me te āwhina AI. He whakamātau, ehara i te taupānga mana a AT."
  },
  "course.checkAT": {
    "en": "Check with AT ↗",
    "mi": "Tirohia ki AT ↗"
  },
  "place.waitemata": {
    "en": "Explore around Waitematā Station",
    "mi": "Tūhuratia te takiwā o Waitematā Station"
  },
  "access.limits": {
    "en": "AT’s current feed does not confirm wheelchair access. The second option may return no journeys. Avoiding mapped barriers does not verify kerbs, lifts, surfaces or the whole route.",
    "mi": "Kāore ngā raraunga AT o nāianei e whakaū i te urunga tūru wīra. Tērā pea kāore he haerenga ka kitea mā te kōwhiringa tuarua. Ahakoa ka karohia ngā ārai kua maherehia, kāore e whakaūngia ngā tapa huarahi, ngā ararewa, ngā papa, te ara katoa rānei."
  },
  "access.at": {
    "en": "AT accessible travel information",
    "mi": "Ngā kōrero AT mō te haere e āhei ana ki te katoa"
  },
  "journey.limits": {
    "en": "Urban Auckland street coverage. Up to 3 changes and a 4-hour search window. Walking follows mapped paths with estimated links to buildings and platforms. Kerbs, lifts and overall accessibility are not verified.",
    "mi": "Ka kapi ngā tiriti o te tāone o Tāmaki Makaurau. Kia kaua e nui ake i te 3 ngā whakawhitinga, ā, e 4 hāora te wā rapu. Ka whai te hīkoi i ngā ara kua maherehia, me ngā hononga whakatau tata ki ngā whare me ngā tūāpapa. Kāore ngā tapa huarahi, ngā ararewa, me te āhei whānui ki te uru i whakaūngia."
  },
  "alerts.title": {
    "en": "Network service updates",
    "mi": "Ngā whakahou ratonga o te whatunga"
  },
  "alerts.at": {
    "en": "View AT service announcements ↗",
    "mi": "Tirohia ngā pānui ratonga AT ↗"
  },
  "footer.independent": {
    "en": "Independent tool using",
    "mi": "He taputapu motuhake e whakamahi ana i"
  },
  "footer.at": {
    "en": "AT data",
    "mi": "ngā raraunga AT"
  },
  "footer.and": {
    "en": "and",
    "mi": "me"
  },
  "footer.about": {
    "en": "About Along ↗",
    "mi": "Mō Along ↗"
  }
});

Object.assign(messages, {
  "guide.title": {
    "en": "Install Along · Offline and private",
    "mi": "Tāutahia a Along · Tuimotu, tūmataiti hoki"
  },
  "guide.back": {
    "en": "← Open Along",
    "mi": "← Huakina a Along"
  },
  "guide.open": {
    "en": "Open Along and prepare this device",
    "mi": "Huakina a Along, ka whakarite i tēnei pūrere"
  }
});

Object.assign(messages, {
  "feedback.title": {
    "en": "Feedback on Along",
    "mi": "Urupare mō Along"
  },
  "feedback.public": {
    "en": "Feedback submitted to GitHub is public. Avoid personal details you do not want to share.",
    "mi": "Ka kitea tūmatanuitia ngā urupare ka tukuna ki GitHub. Kaua e whakauru kōrero whaiaro kāore koe e hiahia ki te tiritiri."
  },
  "feedback.signin": {
    "en": "You need a GitHub account. Review here, then sign in and choose Submit new issue on GitHub to send it.",
    "mi": "Me whai pūkete GitHub koe. Arotakengia ki konei, kātahi ka takiuru, ka kōwhiri Submit new issue ki GitHub hei tuku."
  },
  "feedback.message": {
    "en": "What would you like us to know?",
    "mi": "He aha tāu e hiahia ana kia mōhio mātou?"
  },
  "feedback.local": {
    "en": "Your draft stays on this device until you choose to open GitHub. Maximum 4,000 characters.",
    "mi": "Ka noho tō hukihuki ki tēnei pūrere kia kōwhiri koe ki te huaki i a GitHub. Kia kaua e nui ake i te 4,000 pūāhua."
  },
  "feedback.context": {
    "en": "Include the app version, language and general screen shown below",
    "mi": "Whakaurua te putanga taupānga, te reo me te mata whānui kei raro nei"
  },
  "feedback.review": {
    "en": "Review feedback",
    "mi": "Arotakengia te urupare"
  },
  "feedback.body": {
    "en": "Exact text to share (including the report ID)",
    "mi": "Te tuhinga ka tiritiria (me te ID pūrongo)"
  },
  "feedback.copyHelp": {
    "en": "This report is too long for a prefilled link. Copy this text, open GitHub and paste it into the issue description.",
    "mi": "He roa rawa tēnei pūrongo mō te hononga kua whakakīa. Tāruatia te tuhinga, huakina a GitHub, ka whakapiri ki te whakaahuatanga take."
  },
  "feedback.copy": {
    "en": "Copy report",
    "mi": "Tāruatia te pūrongo"
  },
  "feedback.edit": {
    "en": "Edit draft",
    "mi": "Whakatikaina te hukihuki"
  },
  "feedback.github": {
    "en": "Open GitHub to submit ↗",
    "mi": "Huakina a GitHub hei tuku ↗"
  },
  "feedback.handoff": {
    "en": "Opening GitHub does not confirm submission. After submitting, paste the issue link here to check receipt.",
    "mi": "Kāore te huaki i a GitHub e whakaū kua tukuna. I muri i te tuku, whakapirihia te hononga take ki konei hei tirotiro kua tae atu."
  },
  "feedback.url": {
    "en": "GitHub issue link",
    "mi": "Hononga take GitHub"
  },
  "feedback.check": {
    "en": "Check receipt",
    "mi": "Tirohia kua tae atu"
  },
  "feedback.retry": {
    "en": "Did not submit?",
    "mi": "Kāore i tukuna?"
  },
  "feedback.retryHelp": {
    "en": "Check your GitHub tab first to avoid duplicate reports. Reopening uses the same report ID.",
    "mi": "Tirohia tō ripa GitHub i te tuatahi kia kore ai e tāruarua ngā pūrongo. Ka whakamahia taua ID pūrongo anō ina huaki anō."
  },
  "feedback.notSubmitted": {
    "en": "I have not submitted this report",
    "mi": "Kāore anō ahau kia tuku i tēnei pūrongo"
  },
  "feedback.view": {
    "en": "View received feedback on GitHub ↗",
    "mi": "Tirohia te urupare kua tae atu ki GitHub ↗"
  },
  "feedback.clear": {
    "en": "Clear this draft",
    "mi": "Mukua tēnei hukihuki"
  },
  "feedback.stored": {
    "en": "Draft saved on this device.",
    "mi": "Kua tiakina te hukihuki ki tēnei pūrere."
  },
  "feedback.session": {
    "en": "Storage is unavailable. Keep this window open or copy your text.",
    "mi": "Kāore te rokiroki e wātea ana. Waiho tēnei matapihi kia tuwhera, tāruatia rānei tō tuhinga."
  },
  "feedback.received": {
    "en": "Receipt verified: this report is in the Along repository.",
    "mi": "Kua whakaū kua tae atu: kei te putunga Along tēnei pūrongo."
  },
  "feedback.unverified": {
    "en": "Submission is not yet verified. Your draft is kept here.",
    "mi": "Kāore anō kia whakaūngia te tukunga. Ka puritia tō hukihuki ki konei."
  },
  "feedback.empty": {
    "en": "Write some feedback before reviewing it.",
    "mi": "Tuhia he urupare i mua i te arotake."
  },
  "feedback.offline": {
    "en": "You are offline. Keep the draft and open GitHub when connected.",
    "mi": "Kei te tuimotu koe. Puritia te hukihuki, ka huaki i a GitHub ina hono anō."
  },
  "feedback.copied": {
    "en": "Report copied.",
    "mi": "Kua tāruatia te pūrongo."
  },
  "feedback.selectCopy": {
    "en": "Text selected. Use your device’s Copy action.",
    "mi": "Kua tīpakohia te tuhinga. Whakamahia te mahi Tārua o tō pūrere."
  },
  "feedback.checking": {
    "en": "Checking this issue on GitHub…",
    "mi": "Kei te tirohia tēnei take ki GitHub…"
  },
  "feedback.invalid": {
    "en": "Paste an Along repository issue link after opening GitHub to submit.",
    "mi": "Whakapirihia he hononga take o te putunga Along i muri i te huaki i a GitHub hei tuku."
  },
  "feedback.unavailable": {
    "en": "Receipt could not be checked. Your draft is kept; try again when connected.",
    "mi": "Kāore i taea te tirotiro kua tae atu. Ka puritia tō hukihuki; whakamātau anō ina hono."
  },
  "feedback.mismatch": {
    "en": "This issue does not contain the reviewed report. Check the link or any edits made on GitHub; the draft is kept.",
    "mi": "Kāore tēnei take e mau ana i te pūrongo i arotakengia. Tirohia te hononga, ngā whakatikatika ki GitHub rānei; ka puritia te hukihuki."
  },
  "feedback.open": {
    "en": "Give feedback on this screen",
    "mi": "Tukuna he urupare mō tēnei mata"
  }
});
